### ISSUE TITLE
App Crashes or Pauses between songs

### ISSUE THREAD

**Issue by AndrewReitz** [AndrewReitz/never-ending-splendor#11]
App is randomly stopping or crashing when switching from one song to the next.

**Comment by AndrewReitz** [comment]
This appears to be an issue with the second music player where the app is trying to load the next song to prevent a gap between playback.

**Comment by AndrewReitz** [comment]
Some stacktraces from crashlytics. 

```
Caused by java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter startIntent
       at never.ending.splendor.app.MusicService.onStartCommand(MusicService.java:2)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
       at android.app.ActivityThread.access$1800(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.setNextMediaPlayer(MediaPlayer.java)
       at never.ending.splendor.app.playback.LocalPlayback.onPrepared(LocalPlayback.java:25)
       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3348)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
